service: mexican-vehicles-api
 
provider:
  name: aws
  region: us-east-1
  memorySize: 1024
  timeout: 900
  ecr:
    images:
      mexican-vehicles-api:
        path: ./

functions:
  api:
    url: true
    image:
      name: mexican-vehicles-api
      command:
        - mexican_vehicles_api.api.handler
